---
# handlers file for update-firewall-rules
- name: restart firewalld
  service:
     name: firewalld
     state: restarted
- name: restart ssh 
  service:
     name: ssh
     state: restarted
- name: restart ftp
  service:
     name: ftp
     state: restarted
- name: restart rapidrecovery-agent
  service:
     name: rapidrecovery-agent
     state: restarted
