---

- name: Updating Firewall rules in DEV environment
  hosts: dev
  roles:
    - role: update-firewall-rules-esb
      firewall:
         - { port: 8989, protocol: tcp, zone: public, service: service_name }
         - { port: 8010, protocol: tcp, zone: public, service: service_name }
         - { port: 8082, protocol: tcp, zone: public, service: service_name }
         - { port: 8004, protocol: tcp, zone: public, service: service_name }
         - { port: 8107, protocol: tcp, zone: public, service: service_name }
         - { port: 8161, protocol: tcp, zone: public, service: service_name }
         - { port: 8001, protocol: tcp, zone: public, service: service_name }
         - { port: 8680, protocol: tcp, zone: public, service: service_name }
         - { port: 61616, protocol: tcp, zone: public, service: service_name }
         - { port: 9016, protocol: tcp, zone: public, service: service_name }
         - { port: 9017, protocol: tcp, zone: public, service: service_name }
         - { port: 8117, protocol: tcp, zone: public, service: service_name }
         - { port: 9018, protocol: tcp, zone: public, service: service_name }
         - { port: 9019, protocol: tcp, zone: public, service: service_name }
         - { port: 3030, protocol: tcp, zone: public, service: service_name }
         - { port: 5091, protocol: tcp, zone: public, service: service_name }
