- name: Building list of rules which need to be applied from ranges
  hosts: dev
  tasks:
    - set_fact:
         firewall_ssh: "{{ firewall_ssh | default([]) + [ { 'port': item, 'protocol': 'tcp', 'zone': 'public', 'service': 'service_name' } ] }}"
      loop: "{{ range(35001,35100) | list }}"

    - set_fact:
         firewall_ssh: "{{ firewall_ssh | default([]) + [ { 'port': item, 'protocol': 'udp', 'zone': 'public', 'service': 'service_name' } ] }}"
      loop: "{{ range(35001,35100) | list }}"

- name: Updating Firewall rules in STG environment
  hosts: dev
  roles:
    - role: update-firewall-rules-ftp
      firewall:
        - { port: 22, protocol: tcp, zone: drop, service: service_name }
        - { port: 86, protocol: tcp, zone: drop, service: service_name }
        - { port: 1971, protocol: tcp, zone: drop, service: service_name }
        - { port: 2700, protocol: tcp, zone: drop, service: service_name }
        - { port: 4075, protocol: tcp, zone: drop, service: service_name }
        - { port: 5021, protocol: tcp, zone: drop, service: service_name }
        - { port: 5022, protocol: tcp, zone: drop, service: service_name }
        - { port: 5023, protocol: tcp, zone: drop, service: service_name }
        - { port: 5024, protocol: tcp, zone: drop, service: service_name }
        - { port: 5025, protocol: tcp, zone: drop, service: service_name }
        - { port: 5026, protocol: tcp, zone: drop, service: service_name }
        - { port: 5080, protocol: tcp, zone: drop, service: service_name }
        - { port: 9001, protocol: tcp, zone: drop, service: service_name }
        - { port: 9002, protocol: tcp, zone: drop, service: service_name }
        - { port: 9003, protocol: tcp, zone: drop, service: service_name }
        - { port: 9004, protocol: tcp, zone: drop, service: service_name }
        - { port: 9005, protocol: tcp, zone: drop, service: service_name }
        - { port: 9006, protocol: tcp, zone: drop, service: service_name }
        - { port: 9011, protocol: tcp, zone: drop, service: service_name }
        - { port: 9021, protocol: tcp, zone: drop, service: service_name }
        - { port: 9013, protocol: tcp, zone: drop, service: service_name }
        - { port: 9014, protocol: tcp, zone: drop, service: service_name }
        - { port: 9015, protocol: tcp, zone: drop, service: service_name }
        - { port: 9016, protocol: tcp, zone: drop, service: service_name }
        - { port: 42555, protocol: tcp, zone: drop, service: service_name }
        - { port: 42585, protocol: tcp, zone: drop, service: service_name }
        - { port: 1975, protocol: tcp, zone: drop, service: service_name }
        - { port: 1976, protocol: tcp, zone: drop, service: service_name }
        - { port: 1977, protocol: tcp, zone: drop, service: service_name }
        - { port: 2800, protocol: tcp, zone: drop, service: service_name }
        - { port: 2850, protocol: tcp, zone: drop, service: service_name }
        - { port: 2900, protocol: tcp, zone: drop, service: service_name }
        - { port: 2911, protocol: tcp, zone: drop, service: service_name }
        - { port: 4952, protocol: tcp, zone: drop, service: service_name }
        - { port: 4980, protocol: tcp, zone: drop, service: service_name }
        - { port: 4990, protocol: tcp, zone: drop, service: service_name }
        - { port: 4991, protocol: tcp, zone: drop, service: service_name }
        - { port: 4992, protocol: tcp, zone: drop, service: service_name }
        - { port: 8090, protocol: tcp, zone: drop, service: service_name }
        - { port: 8091, protocol: tcp, zone: drop, service: service_name }
        - { port: 8092, protocol: tcp, zone: drop, service: service_name }
        - { port: 8093, protocol: tcp, zone: drop, service: service_name }
        - { port: 1912, protocol: tcp, zone: drop, service: service_name }
        - { port: 1972, protocol: tcp, zone: drop, service: service_name }
        - { port: 9012, protocol: tcp, zone: drop, service: service_name }
        - { port: 86, protocol: udp, zone: drop, service: service_name }
        - { port: 9007, protocol: tcp, zone: drop, service: service_name }
        - { port: 9017, protocol: tcp, zone: drop, service: service_name }
        - { port: 5027, protocol: tcp, zone: drop, service: service_name }
        - { port: 8190, protocol: tcp, zone: drop, service: service_name }
        - { port: 8191, protocol: tcp, zone: drop, service: service_name }
        - { port: 10083, protocol: tcp, zone: drop, service: service_name }
        - { port: 1717, protocol: tcp, zone: drop, service: service_name }
    - role: update-firewall-rules-ssh
      firewall:
        - { port: 8198, protocol: tcp, zone: public, service: service_name }
        - { port: 8197, protocol: tcp, zone: public, service: service_name }
        - { port: 10084, protocol: tcp, zone: public, service: service_name }
        - { port: 10083, protocol: tcp, zone: public, service: service_name }
        - { port: 8190, protocol: tcp, zone: public, service: service_name }
        - { port: 9191, protocol: tcp, zone: public, service: service_name }
        - { port: 9190, protocol: tcp, zone: public, service: service_name }
        - { port: 2380, protocol: tcp, zone: public, service: service_name }
        - { port: 2704, protocol: tcp, zone: public, service: service_name }
        - { port: 7121, protocol: tcp, zone: public, service: service_name }
    - role: update-firewall-rules-ssh
      firewall: "{{ firewall_ssh }}"
